# @package _global_

model:
  _target_: starter_kit.baselines.cnn.CNNModel
  n_epochs: ${n_epochs}
  learning_rate: ${learning_rate}
  weight_decay: 0.00015594799658456143
  best_threshold: 0.99
  log_csv: true

network:
  _target_: starter_kit.baselines.cnn.CNNNetwork
  in_channels_level: 4
  in_channels_aux: 2
  hidden_dim: 128
  n_levels: 7
  n_blocks: 5
