defaults:
  - data: default
  - model: mlp
  - hydra: default
  - _self_

exp_name: baseline_mlp
store_path: data/models/${exp_name}
use_timestamp: false
device: cuda
seed: 42
n_epochs: 10
batch_size: 32
learning_rate: 0.001
log_wandb: true
wandb_project: ci26_hackathon
